### ISSUE TITLE
Wrong Selector

### ISSUE THREAD

**Issue by BoyanXu** [JianJroh/chatgpt-question-navigator#2]
The Selector selects answers instead of questions:

![image](https://github.com/JianJroh/chatgpt-question-navigator/assets/34408790/3e4fd66a-e806-4805-8053-7990f0e55b49)

Great extension though!

**Comment by JianJroh** [comment]
Hey @BoyanXu, sorry for a slow response. Can you reproduce the problem in the latest version？

**Comment by firimar** [comment]
我这也出现这个问题了，原因是网页最近更新了 flex flex-col text-sm下多了一个header

**Comment by firimar** [comment]
> 我这也出现这个问题了，原因是网页最近更新了 flex flex-col text-sm下多了一个header

把判断条件index%2===0改成 判断 img的alt属性是User，问题得到解决
